/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio, sin secretos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disponibilidad (directorio de datos escribible) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ready: boolean;
                        };
                    };
                };
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indica si falta el asistente inicial */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            setup_required: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea el owner (solo si no hay usuarios) y abre sesión */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupRequest"];
                };
            };
            responses: {
                /** @description Sesión abierta */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
                500: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre sesión con cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Sesión abierta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
                500: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesión */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario, org, rol, csrf y capacidades */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de dispositivos */
        get: {
            parameters: {
                query?: {
                    state?: "inside" | "outside" | "unknown";
                    q?: string;
                    severity?: "low" | "medium" | "high" | "critical" | "unknown";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de dispositivo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Últimas posiciones */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["TrailPoint"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ejecuta una acción sobre un dispositivo con los guardarraíles del motor */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeviceActionRequest"];
                };
            };
            responses: {
                /** @description Resultado de la acción, incluidas la ejecutada en dry-run y la bloqueada por un guardarraíl */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionResult"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de geocercas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FenceList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea una geocerca */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Fence"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fence"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de geocerca */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fence"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye una geocerca */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Fence"];
                };
            };
            responses: {
                /** @description Actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fence"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Elimina una geocerca */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de rutas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea una ruta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de ruta */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye una ruta */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            responses: {
                /** @description Actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Elimina una ruta */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de puntos de interés */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POIList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea un POI */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["POI"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POI"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pois/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** POIs como FeatureCollection */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pois/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de POI */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POI"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye un POI */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["POI"];
                };
            };
            responses: {
                /** @description Actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POI"];
                    };
                };
            };
        };
        post?: never;
        /** Elimina un POI */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de políticas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea una política */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Policy"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catálogo de campos y operadores del editor de políticas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyFieldCatalog"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simula una política candidata contra el histórico (solo lectura) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReplayRequest"];
                };
            };
            responses: {
                /** @description Resumen de la simulación */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReplayResult"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plantillas de política listas para usar */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PolicyTemplateList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de política */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Policy"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye una política */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Policy"];
                };
            };
            responses: {
                /** @description Actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Policy"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Elimina una política */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engine/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del motor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EngineStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engine/run-once": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ejecuta un ciclo ahora */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ciclo ejecutado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CycleStats"];
                    };
                };
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transiciones paginadas, de la más reciente a la más antigua */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    /** @description Cursor opaco devuelto como next_cursor por la página anterior. Ausente empieza por lo más reciente. */
                    cursor?: components["parameters"]["Cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventPage"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Acciones paginadas, de la más reciente a la más antigua */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    /** @description Cursor opaco devuelto como next_cursor por la página anterior. Ausente empieza por lo más reciente. */
                    cursor?: components["parameters"]["Cursor"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActionPage"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bandeja de incidentes */
        get: {
            parameters: {
                query?: {
                    status?: "open" | "ack" | "closed";
                    device_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agregados de la cartera de incidentes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IncidentAnalytics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exporta los incidentes en CSV */
        get: {
            parameters: {
                query?: {
                    status?: "open" | "ack" | "closed";
                    device_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description CSV con cabecera en español y Content-Disposition de descarga */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de incidente */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambia el estado del incidente y anota la auditoría */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["IncidentPatch"];
                };
            };
            responses: {
                /** @description Actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Incident"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reglas de alerta */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertRuleList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea una regla de alerta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertRule"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Vista previa; devuelve los disparos sin notificar ni persistir */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertEvaluation"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de regla de alerta */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertRule"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye una regla de alerta */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AlertRule"];
                };
            };
            responses: {
                /** @description Actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertRule"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Elimina una regla de alerta */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de playbooks SOAR */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlaybookList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea un playbook */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Playbook"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Playbook"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/playbooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de playbook */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Playbook"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye un playbook */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Playbook"];
                };
            };
            responses: {
                /** @description Actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Playbook"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Elimina un playbook */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handoffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bandeja de aprobaciones (pendientes primero) */
        get: {
            parameters: {
                query?: {
                    status?: "pending" | "approved" | "rejected" | "executed";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HandoffList"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handoffs/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aprueba un handoff y ejecuta su acción pasando por los guardarraíles
         * @description Un bloqueo del guardarraíl responde 200 con el resultado bloqueado dentro. Una supresión por cooldown responde 409 code=cooldown con detail.retry_after: la acción no llegó a ejecutarse, pero la decisión ya está sellada, la petición se queda en approved sin result y una segunda aprobación responde 409 code=conflict.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["HandoffDecision"];
                };
            };
            responses: {
                /** @description Handoff decidido, con el resultado de la ejecución dentro */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Handoff"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/handoffs/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rechaza un handoff sin tocar el dispositivo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["HandoffDecision"];
                };
            };
            responses: {
                /** @description Handoff rechazado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Handoff"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ajustes de la organización; los secretos nunca salen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/enforcement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia solo el bloque de enforcement y lo pone en vigor en el acto */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EnforcementSettings"];
                };
            };
            responses: {
                /** @description Ajustes completos ya vigentes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia solo el bloque de webhook; secret es de solo escritura */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookSettingsUpdate"];
                };
            };
            responses: {
                /** @description Ajustes completos ya vigentes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/ntfy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia solo el canal ntfy; token es de solo escritura */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NtfySettingsUpdate"];
                };
            };
            responses: {
                /** @description Ajustes completos ya vigentes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/egress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia solo la allowlist de egress */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EgressSettings"];
                };
            };
            responses: {
                /** @description Ajustes completos ya vigentes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Cambia solo el contexto de riesgo (turnos, riesgo por zona y franja nocturna) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RiskSettings"];
                };
            };
            responses: {
                /** @description Ajustes completos ya vigentes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Settings"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Comprueba los ajustes y las URLs de salida sin guardar ni enviar nada */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SettingsValidationRequest"];
                };
            };
            responses: {
                /** @description Veredicto por canal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SettingsValidation"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            code: string;
            detail?: unknown;
        };
        Point: {
            lat: number;
            lng: number;
        };
        /** @description Estado de un canal de notificación; nunca lleva secretos (spec §6.4) */
        ChannelStatus: {
            enabled: boolean;
            /** @description URL de destino sin userinfo, sin query y sin fragmento */
            target?: string;
            /** Format: date-time */
            last_ok?: string;
            last_error?: string;
            delivered: number;
            failed: number;
        };
        NotifyStatus: {
            webhook: components["schemas"]["ChannelStatus"];
            ntfy: components["schemas"]["ChannelStatus"];
        };
        Health: {
            status: string;
            version: string;
            mode: string;
            enforcement: string;
            web_built: boolean;
            setup_required: boolean;
            engine: {
                running: boolean;
                cycles: number;
                /** Format: date-time */
                last_cycle_at?: string | null;
                interval_seconds: number;
                last_error?: string;
            };
            /** @description Salud del store según el último ciclo del motor (spec §11) */
            persistence: {
                ok: boolean;
                last_error?: string;
            };
            notify: components["schemas"]["NotifyStatus"];
            map: {
                enabled: boolean;
                tiles_url: string;
            };
        };
        SetupRequest: {
            email: string;
            name: string;
            password: string;
            /** @enum {string} */
            mode: "demo" | "empty";
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        User: {
            id: string;
            email: string;
            name: string;
            org: string;
            /** @enum {string} */
            role: "owner" | "admin" | "operator" | "viewer" | "auditor";
            via: string;
        };
        SessionResponse: {
            user: components["schemas"]["User"];
            csrf: string;
            capabilities: string[];
        };
        Inventory: {
            os_version?: string;
            model?: string;
            manufacturer?: string;
            serial_number?: string;
            imei?: string;
            battery_level?: number;
            battery_state?: string;
            storage_total_gb?: number;
            storage_free_gb?: number;
            encryption_enabled?: boolean;
            carrier?: string;
            assigned_user?: string;
            department?: string;
            device_tag?: string;
            /** Format: date-time */
            enrolled_at?: string;
            /** Format: date-time */
            last_checkin?: string;
            management_mode?: string;
            ownership?: string;
            supervised?: boolean;
            lockdown_mode?: boolean;
            apps?: {
                name: string;
                version: string;
            }[];
        };
        /** @description Observaciones; ausente equivale a desconocido, no a false. País/sitio vacíos y mapa sin métricas se omiten. */
        Posture: {
            rooted?: boolean;
            os_outdated?: boolean;
            hardware_health?: {
                [key: string]: string;
            };
            osquery_config_valid?: boolean;
            country?: string;
            site?: string;
        };
        /** @description Evidencia de ubicación, sin enforcement. Métricas omitidas si faltan datos; checks null significa sin evaluar, [] evaluación sin anomalías. */
        Integrity: {
            suspicious: boolean;
            checks: string[] | null;
            speed_kmh?: number;
            distance_km?: number;
        };
        Verdict: {
            score: number | null;
            severity: string;
            reasons: string[];
            matched_policies: string[];
            /** Format: date-time */
            evaluated_at?: string;
            provenance: string;
            verified: boolean;
        };
        Device: {
            id: string;
            name: string;
            platform: string;
            status?: string;
            compliant: boolean | null;
            provider: string;
            provider_refs?: {
                [key: string]: string;
            };
            location: {
                point?: components["schemas"]["Point"];
                accuracy_m?: number;
                source: string;
                /** Format: date-time */
                observed_at: string;
            };
            network: {
                ip?: string;
                ssid?: string;
                bssid?: string;
            };
            inventory: components["schemas"]["Inventory"];
            /** @description Siempre emitido por D01a (vacío si desconocido); opcional para admitir respuestas M1. */
            posture?: components["schemas"]["Posture"];
            /** @enum {string} */
            fence_state: "inside" | "outside" | "unknown";
            inside_fence: string;
            last_inside_fence: string;
            /**
             * Format: date-time
             * @description Origen del reloj de la clave geocerca/estado; ausente si no evaluado.
             */
            fence_state_since?: string;
            /** @description Segundos completos en la misma clave, incluido unknown; siempre emitido por D01c, opcional para M1. No acredita permanencia física ni ejecuta acciones. */
            dwell_seconds?: number;
            route_id?: string;
            /** @enum {string} */
            route_state: "on_route" | "off_route" | "unassigned";
            route_deviation_m?: number;
            risk: components["schemas"]["Verdict"];
            /** @description Siempre emitido por D01b; opcional para admitir respuestas M1. */
            location_integrity?: components["schemas"]["Integrity"];
            /** @description Contenedor pasivo por nombre de señal; ausente si no informado. Sin evaluación de riesgo implícita. */
            signals?: {
                [key: string]: {
                    [key: string]: unknown;
                } | null;
            };
            evaluation_error?: string;
            /** Format: date-time */
            last_report_at: string;
        };
        DeviceList: {
            items: components["schemas"]["Device"][];
            total: number;
        };
        TrailPoint: {
            /** Format: date-time */
            at: string;
            point: components["schemas"]["Point"];
        };
        FenceAction: {
            /** @enum {string} */
            action: "lock" | "wipe" | "message" | "locate" | "reboot" | "clear_passcode" | "set_compliance" | "custom" | "notify";
            /** @enum {string} */
            when: "on_enter" | "on_exit" | "on_violation" | "on_unknown";
            params?: {
                [key: string]: unknown;
            };
            enabled: boolean;
        };
        Fence: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "circle" | "polygon";
            center?: components["schemas"]["Point"];
            radius_m?: number;
            polygon?: components["schemas"]["Point"][];
            rules: {
                violation_interval_cycles?: number;
                dwell_seconds?: number;
            };
            actions: components["schemas"]["FenceAction"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FenceList: {
            items: components["schemas"]["Fence"][];
            total: number;
        };
        Route: {
            id: string;
            name: string;
            corridor_m: number;
            waypoints: components["schemas"]["Point"][];
            device_ids: string[];
            color?: string;
            actions: components["schemas"]["FenceAction"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RouteList: {
            items: components["schemas"]["Route"][];
            total: number;
        };
        POI: {
            id: string;
            name: string;
            category: string;
            tags?: string[];
            point: components["schemas"]["Point"];
            metadata?: {
                [key: string]: string;
            };
        };
        POIList: {
            items: components["schemas"]["POI"][];
            total: number;
        };
        ProviderHealth: {
            ok: boolean;
            error?: string;
            devices: number;
            latency_ms: number;
            /** Format: date-time */
            last_ok?: string;
        };
        /** @description Guardarraíles vigentes del motor (spec §5.4). live_actions es una allowlist cerrada: solo lo listado sale en vivo, y una lista nula equivale a la lista vacía —ninguna acción sale en vivo, todo queda en dry-run—, porque 2.0 falla cerrado (spec §3 principio 3). */
        EnforcementSettings: {
            /** @enum {string} */
            mode: "observe" | "enforce";
            live_actions: string[] | null;
            allow_wipe: boolean;
            wipe_allowlist: string[] | null;
            action_cooldown_seconds: number;
        };
        CycleStats: {
            /** Format: date-time */
            at: string;
            duration_ms: number;
            mode: string;
            devices_total: number;
            inside: number;
            outside: number;
            unknown: number;
            risk_evaluated: number;
            risk_failed: number;
            by_severity: {
                [key: string]: number;
            };
            transitions: number;
            actions_planned: number;
            actions_executed: number;
            actions_suppressed: number;
            actions_blocked: number;
            incidents_opened: number;
            incidents_closed: number;
            alerts_fired: number;
            handoffs_pending: number;
            deliveries: number;
            deliveries_failed: number;
            evaluation_errors: number;
            persistence_errors: number;
            providers: {
                [key: string]: components["schemas"]["ProviderHealth"];
            };
        };
        EngineStatus: {
            mode: string;
            enforcement: components["schemas"]["EnforcementSettings"];
            interval_seconds: number;
            running: boolean;
            cycles: number;
            last_cycle?: components["schemas"]["CycleStats"];
            last_error?: string;
            /** Format: date-time */
            next_cycle_at?: string;
            providers: {
                [key: string]: components["schemas"]["ProviderHealth"];
            };
            incidents_open: number;
            notify: components["schemas"]["NotifyStatus"];
        };
        Playbook: {
            id: string;
            name: string;
            description: string;
            when: components["schemas"]["PolicyCondition"][];
            actions: components["schemas"]["PolicyAction"][];
            enabled: boolean;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PlaybookList: {
            items: components["schemas"]["Playbook"][];
            total: number;
        };
        Handoff: {
            id: string;
            device_id: string;
            device_name: string;
            playbook_id: string;
            playbook_name: string;
            /** @enum {string} */
            action: "lock" | "wipe" | "message" | "locate" | "reboot" | "clear_passcode" | "set_compliance" | "custom" | "notify";
            params?: {
                [key: string]: unknown;
            };
            reason: string;
            /** @enum {string} */
            severity: "low" | "medium" | "high" | "critical";
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "executed";
            /** Format: date-time */
            requested_at: string;
            /** Format: date-time */
            decided_at?: string;
            decided_by?: string;
            note?: string;
            result?: components["schemas"]["ActionResult"];
        };
        HandoffList: {
            items: components["schemas"]["Handoff"][];
            total: number;
        };
        HandoffDecision: {
            note?: string;
        };
        DeviceActionRequest: {
            /** @enum {string} */
            action: "lock" | "wipe" | "message" | "locate" | "reboot" | "clear_passcode" | "set_compliance" | "custom" | "notify";
            params?: {
                [key: string]: unknown;
            };
        };
        Transition: {
            /** Format: date-time */
            at: string;
            device_id: string;
            device_name: string;
            from: string;
            to: string;
        };
        ActionResult: {
            adapter: string;
            ok: boolean;
            device_id: string;
            device_name: string;
            action: string;
            params?: {
                [key: string]: unknown;
            };
            dry_run: boolean;
            simulated: boolean;
            error?: string;
            command_id?: string;
            note?: string;
            /** Format: date-time */
            at: string;
            fence_id?: string;
            trigger?: string;
            route_id?: string;
            policy_id?: string;
            playbook_id?: string;
            /** @enum {string} */
            severity?: "low" | "medium" | "high" | "critical";
            /** @description Solo se emite si true; su ausencia no acredita autorización ni ejecución. */
            blocked?: boolean;
            error_type?: string;
        };
        PolicyCondition: {
            /** @description Uno de los de /api/v1/policies/fields, o "signal:<nombre>.<clave>" para una señal de riesgo */
            field: string;
            /** @enum {string} */
            op: "eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "in" | "contains";
            value: unknown;
        };
        PolicyAction: {
            /** @enum {string} */
            action: "lock" | "wipe" | "message" | "locate" | "reboot" | "clear_passcode" | "set_compliance" | "custom" | "notify";
            params?: {
                [key: string]: unknown;
            };
        };
        Policy: {
            id: string;
            name: string;
            description?: string;
            /** @description Condiciones unidas por AND; una lista vacía nunca dispara y no se puede guardar */
            when: components["schemas"]["PolicyCondition"][];
            actions: components["schemas"]["PolicyAction"][];
            enabled: boolean;
            /**
             * @description Severidad que la política estampa en las acciones que dispara; obligatoria, el servidor rechaza cualquier otro valor con 400
             * @enum {string}
             */
            severity: "low" | "medium" | "high" | "critical";
            source?: string;
            template_id?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PolicyList: {
            items: components["schemas"]["Policy"][];
            total: number;
        };
        PolicyTemplateList: {
            /** @description Plantillas sin fechar; las sella quien las guarda */
            items: components["schemas"]["Policy"][];
            total: number;
        };
        PolicyFieldCatalog: {
            fields: string[];
            ops: ("eq" | "ne" | "gt" | "gte" | "lt" | "lte" | "in" | "contains")[];
        };
        ReplayRequest: {
            policy: components["schemas"]["Policy"];
            /** @description Puntos del histórico a simular. Ausente o menor que 1 usa 5000; por encima de 20000 se acota a 20000, nunca es un error */
            limit?: number;
            /** @description Recalcula el estado de geocerca con las geocercas de hoy en vez de leerlo del histórico de eventos */
            use_current_fences?: boolean;
        };
        ReplaySample: {
            /** Format: date-time */
            at: string;
            device_id: string;
            device_name: string;
            fence_state: string;
            score: number | null;
            severity: string;
            reasons: string[];
        };
        ReplayResult: {
            policy_id: string;
            points_evaluated: number;
            devices_evaluated: number;
            firings: number;
            by_device: {
                [key: string]: number;
            };
            by_action: {
                [key: string]: number;
            };
            /** @description True cuando el resultado no es exacto, porque hay campos que se leen del dispositivo de hoy o porque la permanencia se midió desde la ventana simulada; el motivo concreto va en notes */
            approximation: boolean;
            /** @description Qué se pudo reconstruir y qué no, en español; un cero sin notas sería un falso verde */
            notes: string[];
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
            samples: components["schemas"]["ReplaySample"][];
        };
        IncidentTimelineEntry: {
            /** Format: date-time */
            at: string;
            actor: string;
            from: string;
            to: string;
            note: string;
        };
        Incident: {
            id: string;
            device_id: string;
            device_name: string;
            kind: string;
            severity: string;
            title: string;
            recommendation: string;
            fence_id?: string;
            assignee?: string;
            /** @enum {string} */
            status: "open" | "ack" | "closed";
            risk_score: number | null;
            count: number;
            evidence: string[];
            /** Format: date-time */
            opened_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            acked_at?: string;
            /** Format: date-time */
            closed_at?: string;
            timeline: components["schemas"]["IncidentTimelineEntry"][];
        };
        IncidentList: {
            items: components["schemas"]["Incident"][];
            total: number;
        };
        IncidentPatch: {
            /** @enum {string} */
            status: "open" | "ack" | "closed";
            assignee?: string;
            note?: string;
        };
        IncidentAnalytics: {
            total: number;
            open: number;
            ack: number;
            closed: number;
            by_severity: {
                [key: string]: number;
            };
            by_kind: {
                [key: string]: number;
            };
            by_day: {
                day: string;
                count: number;
            }[];
            /** @description Nulo mientras no haya ningún incidente cerrado con sello; nunca 0 */
            mttr_seconds: number | null;
            top_devices: {
                device_id: string;
                device_name: string;
                count: number;
            }[];
        };
        AlertRule: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "outside_duration" | "risk_above" | "noncompliant" | "battery_below" | "storage_low" | "stale_checkin";
            threshold: number;
            severity: string;
            enabled: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AlertRuleList: {
            items: components["schemas"]["AlertRule"][];
            total: number;
        };
        AlertFiring: {
            /** Format: date-time */
            at: string;
            rule_id: string;
            rule_name: string;
            kind: string;
            device_id: string;
            device_name: string;
            severity: string;
            reason: string;
            value: number;
        };
        AlertEvaluation: {
            /** Format: date-time */
            at: string;
            rules_evaluated: number;
            devices: number;
            count: number;
            firings: components["schemas"]["AlertFiring"][];
        };
        /** @description Canal de webhook firmado. secret_set dice si hay credencial guardada; el valor no sale nunca por la API. */
        WebhookSettings: {
            url: string;
            /** @enum {string} */
            format: "native" | "ocsf";
            events: ("incident.opened" | "incident.closed" | "handoff.pending" | "action.executed" | "alert.fired")[];
            enabled: boolean;
            secret_set: boolean;
        };
        /** @description Cuerpo de PUT /settings/webhooks. secret es de solo escritura: si falta no se toca el secreto guardado, la cadena vacía lo borra y cualquier otro valor lo sustituye. secret_set no se acepta. */
        WebhookSettingsUpdate: {
            url: string;
            /** @enum {string} */
            format: "native" | "ocsf";
            events: ("incident.opened" | "incident.closed" | "handoff.pending" | "action.executed" | "alert.fired")[];
            enabled: boolean;
            secret?: string;
        };
        NtfySettings: {
            url: string;
            enabled: boolean;
            token_set: boolean;
        };
        /** @description Cuerpo de PUT /settings/ntfy. token es de solo escritura: si falta no se toca el token guardado, la cadena vacía lo borra y cualquier otro valor lo sustituye. token_set no se acepta. */
        NtfySettingsUpdate: {
            url: string;
            enabled: boolean;
            token?: string;
        };
        /** @description Allowlist de salida. Vacía deniega todo; allow_private abre RFC1918 y loopback, nunca link-local. */
        EgressSettings: {
            hosts: string[];
            allow_private: boolean;
        };
        RiskSettings: {
            shift_zones: {
                [key: string]: string;
            };
            zone_risk: {
                [key: string]: number;
            };
            off_hours_start: number;
            off_hours_end: number;
        };
        Settings: {
            schema_version: number;
            enforcement: components["schemas"]["EnforcementSettings"];
            webhook: components["schemas"]["WebhookSettings"];
            ntfy: components["schemas"]["NtfySettings"];
            egress: components["schemas"]["EgressSettings"];
            risk: components["schemas"]["RiskSettings"];
            /** Format: date-time */
            updated_at: string;
        };
        /** @description Bloques que el formulario tiene en pantalla. Los ausentes se toman de los ajustes guardados. No acepta el secreto del webhook. */
        SettingsValidationRequest: {
            enforcement?: components["schemas"]["EnforcementSettings"];
            webhook?: components["schemas"]["WebhookSettings"];
            ntfy?: components["schemas"]["NtfySettings"];
            egress?: components["schemas"]["EgressSettings"];
            risk?: components["schemas"]["RiskSettings"];
        };
        SettingsValidationChannel: {
            /** @enum {string} */
            channel: "webhook" | "ntfy";
            enabled: boolean;
            url?: string;
            ok: boolean;
            reason?: string;
            addresses?: string[];
        };
        SettingsValidation: {
            ok: boolean;
            error?: string;
            field?: string;
            channels: components["schemas"]["SettingsValidationChannel"][];
        };
        EventPage: {
            items: components["schemas"]["Transition"][];
            next_cursor: string;
        };
        ActionPage: {
            items: components["schemas"]["ActionResult"][];
            next_cursor: string;
        };
    };
    responses: {
        /** @description Error con forma única */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ID: string;
        Limit: number;
        /** @description Cursor opaco devuelto como next_cursor por la página anterior. Ausente empieza por lo más reciente. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
