/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio, sin secretos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Disponibilidad (directorio de datos escribible) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Listo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ready: boolean;
                        };
                    };
                };
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Indica si falta el asistente inicial */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            setup_required: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crea el owner (solo si no hay usuarios) y abre sesión */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupRequest"];
                };
            };
            responses: {
                /** @description Sesión abierta */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
                500: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abre sesión con cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Sesión abierta */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
                401: components["responses"]["Error"];
                429: components["responses"]["Error"];
                500: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cierra la sesión */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario, org, rol, csrf y capacidades */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de dispositivos */
        get: {
            parameters: {
                query?: {
                    state?: "inside" | "outside" | "unknown";
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeviceList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de dispositivo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Device"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Últimas posiciones */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["TrailPoint"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de geocercas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FenceList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea una geocerca */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Fence"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fence"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de geocerca */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fence"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye una geocerca */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Fence"];
                };
            };
            responses: {
                /** @description Actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Fence"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Elimina una geocerca */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de rutas */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RouteList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea una ruta */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de ruta */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye una ruta */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            responses: {
                /** @description Actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Route"];
                    };
                };
                400: components["responses"]["Error"];
                404: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Elimina una ruta */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pois": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de puntos de interés */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POIList"];
                    };
                };
            };
        };
        put?: never;
        /** Crea un POI */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["POI"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POI"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pois/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** POIs como FeatureCollection */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: unknown;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pois/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de POI */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POI"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Sustituye un POI */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["POI"];
                };
            };
            responses: {
                /** @description Actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["POI"];
                    };
                };
            };
        };
        post?: never;
        /** Elimina un POI */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ID"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Eliminado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engine/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del motor */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EngineStatus"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engine/run-once": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ejecuta un ciclo ahora */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ciclo ejecutado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CycleStats"];
                    };
                };
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Últimas transiciones */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Transition"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Últimas acciones ejecutadas */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["ActionResult"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            code: string;
            detail?: unknown;
        };
        Point: {
            lat: number;
            lng: number;
        };
        Health: {
            status: string;
            version: string;
            mode: string;
            enforcement: string;
            web_built: boolean;
            setup_required: boolean;
            engine: {
                running: boolean;
                cycles: number;
                /** Format: date-time */
                last_cycle_at?: string | null;
                interval_seconds: number;
                last_error?: string;
            };
            /** @description Salud del store según el último ciclo del motor (spec §11) */
            persistence: {
                ok: boolean;
                last_error?: string;
            };
            map: {
                enabled: boolean;
                tiles_url: string;
            };
        };
        SetupRequest: {
            email: string;
            name: string;
            password: string;
            /** @enum {string} */
            mode: "demo" | "empty";
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        User: {
            id: string;
            email: string;
            name: string;
            org: string;
            /** @enum {string} */
            role: "owner" | "admin" | "operator" | "viewer" | "auditor";
            via: string;
        };
        SessionResponse: {
            user: components["schemas"]["User"];
            csrf: string;
            capabilities: string[];
        };
        Inventory: {
            os_version?: string;
            model?: string;
            manufacturer?: string;
            serial_number?: string;
            imei?: string;
            battery_level?: number;
            battery_state?: string;
            storage_total_gb?: number;
            storage_free_gb?: number;
            encryption_enabled?: boolean;
            carrier?: string;
            assigned_user?: string;
            department?: string;
            device_tag?: string;
            /** Format: date-time */
            enrolled_at?: string;
            /** Format: date-time */
            last_checkin?: string;
            management_mode?: string;
            ownership?: string;
            supervised?: boolean;
            lockdown_mode?: boolean;
            apps?: {
                name: string;
                version: string;
            }[];
        };
        Verdict: {
            score: number | null;
            severity: string;
            reasons: string[];
            matched_policies: string[];
            /** Format: date-time */
            evaluated_at?: string;
            provenance: string;
            verified: boolean;
        };
        Device: {
            id: string;
            name: string;
            platform: string;
            status?: string;
            compliant: boolean | null;
            provider: string;
            provider_refs?: {
                [key: string]: string;
            };
            location: {
                point?: components["schemas"]["Point"];
                accuracy_m?: number;
                source: string;
                /** Format: date-time */
                observed_at: string;
            };
            network: {
                ip?: string;
                ssid?: string;
                bssid?: string;
            };
            inventory: components["schemas"]["Inventory"];
            /** @enum {string} */
            fence_state: "inside" | "outside" | "unknown";
            inside_fence: string;
            last_inside_fence: string;
            route_id?: string;
            /** @enum {string} */
            route_state: "on_route" | "off_route" | "unassigned";
            route_deviation_m?: number;
            risk: components["schemas"]["Verdict"];
            evaluation_error?: string;
            /** Format: date-time */
            last_report_at: string;
        };
        DeviceList: {
            items: components["schemas"]["Device"][];
            total: number;
        };
        TrailPoint: {
            /** Format: date-time */
            at: string;
            point: components["schemas"]["Point"];
        };
        FenceAction: {
            /** @enum {string} */
            action: "lock" | "wipe" | "message" | "locate" | "reboot" | "clear_passcode" | "set_compliance" | "custom" | "notify";
            /** @enum {string} */
            when: "on_enter" | "on_exit" | "on_violation" | "on_unknown";
            params?: {
                [key: string]: unknown;
            };
            enabled: boolean;
        };
        Fence: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "circle" | "polygon";
            center?: components["schemas"]["Point"];
            radius_m?: number;
            polygon?: components["schemas"]["Point"][];
            rules: {
                violation_interval_cycles?: number;
                dwell_seconds?: number;
            };
            actions: components["schemas"]["FenceAction"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FenceList: {
            items: components["schemas"]["Fence"][];
            total: number;
        };
        Route: {
            id: string;
            name: string;
            corridor_m: number;
            waypoints: components["schemas"]["Point"][];
            device_ids: string[];
            color?: string;
            actions: components["schemas"]["FenceAction"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RouteList: {
            items: components["schemas"]["Route"][];
            total: number;
        };
        POI: {
            id: string;
            name: string;
            category: string;
            tags?: string[];
            point: components["schemas"]["Point"];
            metadata?: {
                [key: string]: string;
            };
        };
        POIList: {
            items: components["schemas"]["POI"][];
            total: number;
        };
        ProviderHealth: {
            ok: boolean;
            error?: string;
            devices: number;
            latency_ms: number;
            /** Format: date-time */
            last_ok?: string;
        };
        CycleStats: {
            /** Format: date-time */
            at: string;
            duration_ms: number;
            mode: string;
            devices_total: number;
            inside: number;
            outside: number;
            unknown: number;
            transitions: number;
            actions_planned: number;
            actions_executed: number;
            evaluation_errors: number;
            persistence_errors: number;
            providers: {
                [key: string]: components["schemas"]["ProviderHealth"];
            };
        };
        EngineStatus: {
            mode: string;
            enforcement: string;
            interval_seconds: number;
            running: boolean;
            cycles: number;
            last_cycle?: components["schemas"]["CycleStats"];
            last_error?: string;
            /** Format: date-time */
            next_cycle_at?: string;
            providers: {
                [key: string]: components["schemas"]["ProviderHealth"];
            };
        };
        Transition: {
            /** Format: date-time */
            at: string;
            device_id: string;
            device_name: string;
            from: string;
            to: string;
        };
        ActionResult: {
            adapter: string;
            ok: boolean;
            device_id: string;
            device_name: string;
            action: string;
            params?: {
                [key: string]: unknown;
            };
            dry_run: boolean;
            simulated: boolean;
            error?: string;
            command_id?: string;
            note?: string;
            /** Format: date-time */
            at: string;
            fence_id?: string;
            trigger?: string;
        };
    };
    responses: {
        /** @description Error con forma única */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        ID: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
